// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worktree.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	worktree.proto

It has these top-level messages:
	SaveReq
	SaveResp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type SaveReq struct {
}

func (m *SaveReq) Reset()                    { *m = SaveReq{} }
func (m *SaveReq) String() string            { return proto1.CompactTextString(m) }
func (*SaveReq) ProtoMessage()               {}
func (*SaveReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SaveResp struct {
}

func (m *SaveResp) Reset()                    { *m = SaveResp{} }
func (m *SaveResp) String() string            { return proto1.CompactTextString(m) }
func (*SaveResp) ProtoMessage()               {}
func (*SaveResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*SaveReq)(nil), "proto.SaveReq")
	proto1.RegisterType((*SaveResp)(nil), "proto.SaveResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WorktreeService service

type WorktreeServiceClient interface {
	Save(ctx context.Context, in *SaveReq, opts ...grpc.CallOption) (*SaveResp, error)
}

type worktreeServiceClient struct {
	cc *grpc.ClientConn
}

func NewWorktreeServiceClient(cc *grpc.ClientConn) WorktreeServiceClient {
	return &worktreeServiceClient{cc}
}

func (c *worktreeServiceClient) Save(ctx context.Context, in *SaveReq, opts ...grpc.CallOption) (*SaveResp, error) {
	out := new(SaveResp)
	err := grpc.Invoke(ctx, "/proto.WorktreeService/Save", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorktreeService service

type WorktreeServiceServer interface {
	Save(context.Context, *SaveReq) (*SaveResp, error)
}

func RegisterWorktreeServiceServer(s *grpc.Server, srv WorktreeServiceServer) {
	s.RegisterService(&_WorktreeService_serviceDesc, srv)
}

func _WorktreeService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorktreeServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WorktreeService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorktreeServiceServer).Save(ctx, req.(*SaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorktreeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WorktreeService",
	HandlerType: (*WorktreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _WorktreeService_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worktree.proto",
}

func init() { proto1.RegisterFile("worktree.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xcf, 0x2f, 0xca,
	0x2e, 0x29, 0x4a, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x9c,
	0x5c, 0xec, 0xc1, 0x89, 0x65, 0xa9, 0x41, 0xa9, 0x85, 0x4a, 0x5c, 0x5c, 0x1c, 0x10, 0x66, 0x71,
	0x81, 0x91, 0x0d, 0x17, 0x7f, 0x38, 0x54, 0x7d, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90,
	0x26, 0x17, 0x0b, 0x48, 0x5a, 0x88, 0x0f, 0x62, 0x80, 0x1e, 0x54, 0x9b, 0x14, 0x3f, 0x0a, 0xbf,
	0xb8, 0x40, 0x89, 0x21, 0x89, 0x0d, 0x2c, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x47, 0xac,
	0xdd, 0x3c, 0x74, 0x00, 0x00, 0x00,
}
